# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{roxyPackage}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab roxyPackage\cr
#' Type: \tab Package\cr
#' Version: \tab 0.10-1\cr
#' Date: \tab 2022-07-07\cr
#' Depends: \tab R (>= 3.0.0)\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://reaktanz.de/?c=hacking&s=roxyPackage\cr
#' }
#'
#' @title
#' \packageTitle{roxyPackage}
#' @author
#' \packageAuthor{roxyPackage}
#'
#' Maintainer: \packageMaintainer{roxyPackage}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL